/**
 * A property bag of known canonical contracts.
 */
const CONTRACTS = {
  DELPHI: {
    MINTER: 'KT1QiQzKvibocEPYXvUKaRAJirNuu4q1cQnF',
    OVEN_PROXY: 'KT1CYCG5SB1KFps64kYwcXic3c1yxUWAZR3G',
    OVEN_FACTORY: 'KT1KCHvFSS5MN9v7cvHuRTGqv69EgGc8gWDu',
    TOKEN: 'KT1RXpLtz22YgX24QQhxKVyKvtKZFaAVtTB9',
    OVEN_REGISTRY: 'KT1LzTVQEhmXG4BTFyPr9afQVBs9y7xGt9WG',
    DEVELOPER_FUND: 'KT1R5rVx46MkRTDXXDiqfTShUiHTvxvLcr3i',
    STABILITY_FUND: 'KT1QWy7BNWLyb1rcPpkMV7RYbDbADGpdYUQk',
    ORACLE: 'KT1VYqsLswpVGcuW51Q9KVXsDQFiXv6RtRj4',
    HARBINGER_NORMALIZER: 'KT1LWDzd6mFhjjnb65a1PjHDNZtFKBieTQKH',
    KOLIBRI_BAKER: 'tz3WXYtyDUNL91qfiCJtVUX746QpNv5i5ve5',
    DEXTER_POOL: 'KT1XTUGj7Rkgh6vLVDu91h81Xu2WGfyTxpqi',
    GOVERNOR: 'KT19gvNq58AknfgmsafeQZUR1PfmTAeZLFrb',
    PAUSE_GUARDIAN: 'KT1UNofBj6bhLq2KaSCdZ2sxJG3U8tn6B4GN',
    FUND_ADMIN: 'KT1P3iM8NS3421bFafvsLHBFSFA1vrzcarqo',
  },
  // NOTE: This is Edo2Net but naming is 'EDO' for consistency.
  EDO: {
    MINTER: 'KT1HerTuyyZBEX5Gtr6GvCjwgPL36p4jPsXX',
    OVEN_PROXY: 'KT1K3DSsQJha7HiYzVvuHUpEiubFPihPvq8Y',
    OVEN_FACTORY: 'KT1BQH1okg2cMg88P8CwRgiNvUpNBSh87PKv',
    TOKEN: 'KT1NSxh1bBJxHkT5ScXwzg4LcuNYQY1abrjR',
    OVEN_REGISTRY: 'KT1VzD6ttSzh7tG8WNvVnkBMi7roRCUoDQk1',
    DEVELOPER_FUND: 'KT1HKd8xE9nJe3JGMoE4hy4fHLvBiekd5Nnz',
    STABILITY_FUND: 'KT1Gjexj6kdDPgf1GDTboCiJyUwGUBcu9bzc',
    ORACLE: 'KT1AnzCgiibDXkWiakufXjBUeUtzuWNdNAXe',
    HARBINGER_NORMALIZER: 'KT1RCNpUEDjZAYhabjzgz1ZfxQijCDVMEaTZ',
    // Below values are not applicable to testnet deployment.
    KOLIBRI_BAKER: 'tz3WXYtyDUNL91qfiCJtVUX746QpNv5i5ve5',
    DEXTER_POOL: '',
    GOVERNOR: '',
    PAUSE_GUARDIAN: '',
    FUND_ADMIN: '',
  },
  MAIN: {
    MINTER: 'KT1Ty2uAmF5JxWyeGrVpk17MEyzVB8cXs8aJ',
    OVEN_PROXY: 'KT1JdufSdfg3WyxWJcCRNsBFV9V3x9TQBkJ2',
    OVEN_FACTORY: 'KT1Mgy95DVzqVBNYhsW93cyHuB57Q94UFhrh',
    TOKEN: 'KT1K9gCRgaLRFKTErYt1wVxA3Frb9FjasjTV',
    OVEN_REGISTRY: 'KT1Ldn1XWQmk7J4pYgGFjjwV57Ew8NYvcNtJ',
    DEVELOPER_FUND: 'KT1SorR4UFBkUJeYVbtXZBNivUV1cQM6AqRR',
    STABILITY_FUND: 'KT18wngSoTUqEJiNaYuhcrfYCtsczLUVVkTp',
    ORACLE: 'KT1Tj6xknbwjyK5gyfESNR6WESBcP3yX1mmj',
    HARBINGER_NORMALIZER: 'KT1AdbYiPYb5hDuEuVrfxmFehtnBCXv4Np7r',
    KOLIBRI_BAKER: 'tz1abmz7jiCV2GH2u81LRrGgAFFgvQgiDiaf',
    DEXTER_POOL: 'KT1AbYeDbjjcAnV1QK7EZUUdqku77CdkTuv6',
    GOVERNOR: 'KT1JBmbYxTv3xptk2CadgEdMfjUCUXKEfe5u',
    PAUSE_GUARDIAN: 'KT1VWKfxhcwJ8H7aRYEYjwaqAfBSQk4J7zAw',
    FUND_ADMIN: 'KT1Le2tWBZv8KLQKJmZfLTVYiyaTELtx6zQW',
  },
}

export default CONTRACTS
